# 토픽 분석
- 문서 속에 숨겨진 주제(Topic)를 자동으로 찾아내는 기법
- LDA는 다음과 같은 두 가지 기본 가정을 따른다.
    1. 문서는 여러 주제(토픽)의 조합이다.
        - 예: "스포츠 기사"는 50% 축구 + 30% 농구 + 20% 야구 주제로 구성될 수 있다.
    2. 각 주제는 여러 단어의 조합이다.
        - 예: 축구라는 주제는 "골", "선수", "리그", "경기" 등의 단어가 자주 등장한다.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('result.csv')
df = df.dropna()
df = df.reset_index()
df = df.drop(columns=['index','작성자','평점','날짜'])
df

                                                  리뷰내용
0           오늘의 포인트를 하려면 업데이트를.하라고 문구가 뜨는데 업데이트가 되지 않음
1                                                  좋아요
2                                                  편리함
3                                                재미있어요
4                                                잘모르겠음
..                                                 ...
140  앱은 편리하고 좋은데 관리하시는분들이 너무 편하게 일하려는듯한 느낌을받았어요...이...
141                                                  👍
142                              했는데도 계속 업데이트 하라고 뜨네요ㅠ
143                       앱은 작동하고 서비스가있지만다음내용화면이 알수없는것
144  이번주 미션 하려면 업데이트하라고 나오는데, 업데이트 버튼이 아예 없네요. 그리고 ...

[145 rows x 1 columns]

In [3]:
import os
os.environ["JAVA_HOME"] = r"C:\Program Files\Java\jdk-21.0.11"

from konlpy.tag import Okt
import re
from tqdm import tqdm   # 진행 상황을 시각적으로 보여주는 라이브러리

In [4]:
def tokenize_text(text):
    text = re.sub(r'[^ㄱ-ㅣ가-힝\s]', '', text)     # 정규표현식으로 텍스트 정제
    
    okt = Okt()
    okt_data = okt.pos(text)                       # (단어, 품사) 형태의 튜플 리스트 반환

    words = []
    for word, pos in okt_data:
        if pos in ['Adjective', 'Noun', 'Verb']:   # 형용사, 명사, 동사만 추출
            words.append(word)


    word_str = ' '.join(words)                     # 단어들을 공백으로 연결하여 하나의 문자열로 반환
    return word_str

In [6]:
token_list = []                     # 각 댓글에서 추출된 토큰 문자열을 저장할 리스트

for text in tqdm(df['리뷰내용']):        # 댓글 데이터 처리 진행 상황 표시
    result = tokenize_text(text)    # tokenize_text 함수를 사용해서 텍스트 정제, 단어 추출
    token_list.append(result)

  0%|          | 0/145 [00:00<?, ?it/s]

100%|██████████| 145/145 [00:06<00:00, 22.29it/s]

In [7]:
token_list

['오늘 포인트 하려면 업데이트 하라 문구 뜨는데 업데이트 되지 않음',
 '좋아요',
 '편리함',
 '재미있어요',
 '모르겠음',
 '수수료 없고 매일 자주 좋은데 방송 봤는데 포인트 들어오구 업뎃 하래 했는데 계속 업뎃해 이용 가능하다 뜨고 업뎃 벌써 번하는거 같은데 언제 반영 되나요',
 '매우 좋음',
 '통장 잔액 보려고 할 때 재부팅 느린 건지 잔액 얼마 남았는지 확인 하는데 많은 시간 걸림',
 '재미 삼아 날 앱 열고 하고있습니다',
 '포인트 원 원 주지 원 시오',
 '좋습니다',
 '공유 합니다',
 '사용 하기 편리해서 좋아요',
 '아주 좋아요',
 '앱 실행 하면 상단 대출 광고 뜹니다 표시 눌러도 계속 뜹니다 길거리 명함 뿌리는 사채 업자 뭐 다릅니까',
 '좋아요',
 '일주일 방문 미션 할 때 가끔 정답 맞혀도 정답 인정 안되고 그럴 때 있는데 즐겁게 토스 앱 이용 하고 있습니다',
 '이번 미션 이안 열려요',
 '토스 작동 않내요 고쳐주세요',
 '편리해요',
 '업데이트 무한 반복 열기 눌렀는데도 계속 제자리 서버 안정화 시키고 실행 시키시지요',
 '환급 해준다면서 준비 서류 안내 순서대로 결제 하니까 마지막 서류 요구 키 서류 있었으면 종 세 경정 청구 했겠지 장난 까냐 부동산 없어져서 류구 지도 하는데 염장 지르네 돈 벌 먹으세요 엔화 장난 치더니 이제 환급 장난 질',
 '보기 복권 만원 만원 기본 원 저 원 원 원 주 윈입니 매일 걸으면 뭐합 너무합니다 사람 차별 하나요 아님 저 무시 하는 겁',
 '유용하게 사용 입니다',
 '토스 측 돈독 올랐는지 게 환급금 수수료 때 먹구 싶어서 알림 설정 전부 해제 해도 거슬리게 배너 띄우고 욕 나오게 만듭니',
 '공유 해요',
 '미션 클릭 하면 업데이트 하라 뜨고 업데이트 안됨',
 '조아요',
 '월 일 이번 주 미션 오늘 포인트 미션 바뀌었는데 언제 이용 가능하게 해주실건 가요 업데이트 하는데 이틀 업데이트 하라 플레이스토어 앱 나오지도 않네요 포인트 얻지 말 건가 그럴거면 차라리 이전 것 되돌려 놓으세요',
 '수수료 먼저 받아가는게 말 되냐 수수료 안내 미리 정차 끝나면 요구 해야지 먼 홈택스 비번 만들래 인증서 쓰면 되는걸 앱 만드는거니까 홈택스 정식 비번 같지도 않음 환불 금방 되는게 장점',
 '굿',
 '이번 업데이트 했는데 이번 주 미션 들어가면 자꾸 업데이트 하라 무한 반복 뜨는데 해결 방법 좀 알려 주세요',
 '주로 사용 하는 유용한 앱임',
 '저',
 '은행 앱 가장 나은듯',
 '그 환급 액 알림 문자 동의 계속 새로 생 성하는거 짜치지 않나요',
 '오늘 미션 안되네요 업데이트 떠서 했는데도 뭐 계속 업데이트 하래 캐시 삭제 재부팅 후 무한 업데이트 팝업',
 '증권 팔로우 친구 사고팔면 알람 뜨는거 간전 사고 팔았는데 이제 알람 뜨면 머합 일 똑바로 하세요',
 '업데이트 했는데 이번 미션 되지도 않고',
 '이번 업뎃 하고부터 이번 주 미션 창 열리질 않네요 클릭 하면 업데이트 해라고만 나오네요 댓글 나오는데로 해도 안되네요',
 '계속 업데이트 요구',
 '에러 많음 트래핑 좀',
 '이번 내 계좌 전체 보기 금리 좋은 상품 모음 남는 돈 주식 투자 하려면 등 생뚱맞 추가 된 부분 역대 최악 패치 봄 거 내 계좌 및 자산 보는데 흐름 끊기고 심지어 오프 안되는 강제 임 진짜 앱 용하는데 불편하고 불쾌함',
 '어려워요',
 '계속 업데이트 화면 뜸',
 '오늘 미션 업데이트 후 한다더니 아니라 일 안 되고 계속 업데이트 하라 하네요 뭔가',
 '앱 거저 거 계속 추가 하더니 앱 무거워 짐',
 '이번 주 미션 업데이트 언제 해줄건 가요 늦어요',
 '숨쉬듯 사용 합니다',
 '항상 잘 사용 있어요',
 '토스 컴 그거 때문 어플 지움',
 '이벤트 다양하고 좋음',
 '일주일 미션 참여 하려면 앱 업데이트 시켜야 한다고 해놓고 정작 구글 플레이스토어 들어가면 업데이트 할수 없게 해놓은 건 무슨 경우 어플 개선 의지 있으시다면 구글플레이 토스 항목 업데이트 버튼 만들어 주시 감사하겠습니다',
 '하시면 돈 생겨요 허루 하루 화이팅',
 '좋아요 재미있고요',
 '한',
 '업데이트 해서 했는데 열림 업데이트 했는데 업데이트 또 거지 업데이트 안되고 열리지도 않고 제거 있구만 쓰레기',
 '쓸데없는 알림 많습니다 분명히 설정 결제 입출금 알림 제외 껏 는데도 불구 같은 내용 불필요한 알림 계속 와서 점점 인내심 한계 느낍니다 처음 사용 경험 좋아 주 통장 토스 바꾼 후 년 넘게 잘 사용 있지만 요즘 들어 그 좋았던 사용 경험 점점 사라지고 어지러운 광고 불편한 불필요한 광고 토스 컴 알람 사람 불편하게 합니다 요즘 내 왜 굳이 이 앱 사용 있지라는 생각 점점 많아지고있고 주변 들 같은말을 합니다',
 '굿',
 '게임 미션 많아요 채널 추가 구독 미션 더 늘려 주시 감사하겠습니다 안녕하세요 미니 앱 포인트 볼 서비스 멈춰있는데 앞 이용 할수 없나요',
 '오늘 미션 오류 좀 이상하네요',
 '좋와 요',
 '진실 합니다 매력 입니다',
 '현금화 편리함 모은 포인트 현금 가치 가지 토스 뱅크 본인 계좌 수수료 조건 따라 바로 출금 거나 결제 시 현금 쓸 수 있습니다 현금화 편리함 모은 포인트 현금 가치 가지 토스 뱅크 본인 계좌 수수료 조건 따라 바로 출금 거나 결제 시 현금 쓸 수 있습니다',
 '이번 주 미션 달라졌어요 월 일 더 많은 혜택 드리는 오늘 포인트 미션 바뀌어요 업데이트 말 무한 반복 하네요 안되는 것 달라졌나요',
 '좋아요',
 '업데이트 하고 안되네요 삭제 다시 해도 안되네요 업데이트 하면 좋아져야 하는거 아닐까 요 왜 안되나요',
 '좋아요',
 '오늘 포인트 미션 하라 업데이트 하라 데 종이 업데이트 안됩니다 종 때문 같은데 폰 바꾸면 토스 못 쓰게 되는걸 까요',
 '광고 토스 인기 컨텐츠 찾기 심 듦',
 '숨기 보기 쉽게 광고 많음',
 '복잡해 불편함',
 '업데이트 했는데 자꾸 업데이트 뜨는 이유 뭐',
 '이번 미션 업데이트 하라 데 안됨 이틀 함 포인트 주기 싫음 말던가 있지도 않은 업데이트 하라',
 '좋아요',
 '이번 미션 실행 문제 가 있습니다 일 미션 하려 누르면 업뎃하 앱스토어 연결 업뎃 안되고 같은 오류 계속 됩니다 캐쉬 삭제 해보고 앱 삭제 후 다시 설치 해도 동일하네요 해결 방법 알려주세요',
 '게임 주',
 '이번 미션 오늘 갑자 기안 들어가 집니다 오류 수정 해주세여',
 '',
 '모든 은행 잔액 수수료 무료 간편 이체 좋아요 대 엄마 토스 잘 쓰세요',
 '오늘 미션 확인 해주세요 토스 업데이트 했는데도 계속 업데이트 필요하다며 업데이트 버튼 무한 루프 입니다 업데이트 버튼 또 눌러도 그냥 토스 앱 이동 하구요',
 '오늘 미션 이용 하려면 앱 업데이트 하라 면서 정작 업데이트 누르면 플레이 스토어 업데이트 버튼 없습니다',
 '잘 사용 있어요',
 '앱 하면 즐겁고 재미 있어요',
 '업데이트 이 용하라는데 업데이트 사람 있긴 함 앱 업데이트 순차 배포 게 말 되나싶네 업데이트 무슨 선착순 미션 아니고 어이 좀 없네',
 '편해요',
 '금융 지식 도움 됩니다 시중 은행 보다 금리 좋구요',
 '포인트 모으기 좋아요',
 '오늘 미션 눌르면 업데이트 하기 뜨고 그거 눌르면 구글플레이 토스 열기 뜨고 다시 오늘 미션 화면 가면 같은 현상 반복 장난 하나',
 '쉽게 사용 할수있어 좋아요 은행 갈 필요 없어요',
 '조 요',
 '좋아요',
 '좋아서요 유익했고요 앞 계속 애용 할 겁니다',
 '포인트 쌓이고 다양하게 사용 할수 있어서 편리하고 좋아요',
 '쪼',
 '업데이트 왜 안되는데 사흘 이러고 있으니 짜증 나려고 하네요',
 '좋아요',
 '사용 하고이습니다 편하게 생각 있습니다',
 '빠르고 편리한 금융 거래 및 정보 제공',
 '엉망 업뎃 했는데도 열어 보면 안되고 또 업뎃 하라 함',
 '좋아요',
 '이번 미션 업데이트 했는데 자꾸 업데이트 고만하고 열려요 업데이트 해서 더 불편해요',
 '좋아요',
 '업데이트 됌',
 '쉽게 다가 갈수 있어서 좋아요',
 '모르 르 정보 뮤 좋아요',
 '잘 사용 있습니다',
 '잘쓰고있습니다',
 '매우 유용함',
 '돈 모으고 재미 있어요',
 '좋음 강추',
 '사용 하기 편해요',
 '좋아요',
 '아주 좋아요 다만 광고 좀 줄여 주시길',
 '대박',
 '최고',
 '되는걸 아예 안되게 해놨네요 자체 안보 여요',
 '아주 좋아요',
 '운동 도나 포인트 받기 좋아요',
 '금융 통합 편리함',
 '',
 '용돈 생기 최고 입니다',
 '왜 매달 원 빠저 나갑니까 달 사용 하는 사용 요금 입 그것 잘 하고 있습니다',
 '아주 좋아요',
 '토스 잘 사 용히고 있습니다 토스 증권 다양한 주식 구매 방법 있는데 새로운 기적 구매 방법 대한 아이디어 있어 작성 합니다 특정 주식 배당금 나오면 자동 주식 배당금 나온 금액 만큼 다시 그 주식 구매 해주는 기능 있다면 좋겠다 생각 합니다',
 '앱 사용 편리했으면 합니다',
 '증권 분봉 차트 날짜 구분 선 설정 체크 해제 했는데 구분 선 안 사라져요 프로그램 거래 량 매도 수량 매수 수량 왜 토스 증권 달라 제 증권사 곳 보는데 곳 일치 하는데 토스 증권 달라',
 '굿굿굿',
 '업데이트 하라 해서 했는데 않 됨',
 '업데이트 헤 이용 가능한 부분 무한 반복 구글 앱 업데이트 없음',
 '포인트 싸이 굿',
 '참 좋아요',
 '왜 복잡해요 노인 잘이 용하기 힘들어오',
 '유용한 앱',
 '좋은데 은행 점검 시간 홈 대문짝만하게 점검 시간 표시 됐으면 좋겠어요 매번 잊어버리고 역 확인 하는데 점검 시간 메시지 뒤늦게 뜨는 게 불편해요',
 '이상해',
 '굿',
 '송금 편리하고 좋은 상품 가격 저렴하고 만족',
 '조아요',
 '상품 광고 보 좋은 제품 많아 좋은 것 같아요',
 '앱 편리하고 좋은데 관리 하시는 분 편하게 일 하려는듯 느낌 받았어요 이용자 다소 불편해도 관리 하시는 분 편할 수 있도 륵 그런 일 하시는듯 느낌 편하지만 곧 사라질것 같은 앱 듯 해',
 '',
 '했는데도 계속 업데이트 하라 뜨네요',
 '앱 작동 서비스 있지만 다음 용화면 알수 없는것',
 '이번 주 미션 하려면 업데이트 나오는데 업데이트 버튼 아예 없네요 보기 긁기하며 포인트 나오지 않고 당연히 적립 돼요']

In [8]:
# 토픽 모델링에서는 너무 짧은 문서가 
corpus_list = []

# 모든 토큰화된 문장을 순회하며 짧은 문장 찾기
for index in range(len(token_list)):
    corpus = token_list[index]

    # 문장을 공백으로 분할 -> set으로 중복 제거 -> 고유 단어 개수 확인
    if len(set(corpus.split())) < 3:        # 고유 단어가 3개 미만인 경우
        corpus_list.append(corpus)

for corpus in corpus_list:
    token_list.remove(corpus)

print(len(token_list))

96

# LDA 작동 과정

1. 모든 단어와 문서를 랜덤하게 주제에 할당
    - 처음에는 랜덤하게 각 단어가 어떤 주제에 속하는지 정한다.
    - 예: "축구"라는 단어가 "스포츠" 주제에 배정될 수도, "정치" 주제에 배정될 수도 있다.

2. 단어의 주제를 반복적으로 재할당
    - 각 단어의 주제 분포를 고려해 더 적합한 주제로 배정한다.
    - 예: "축구"라는 단어가 "스포츠" 주제에서 자주 등장한다면 점점 스포츠 주제로 배정된다.

3. 수렴할 때까지 반복
    - 모든 단어가 가장 적절한 주제에 할당될 때까지 반복한다.

4. 결과 출력: 문서의 토픽 분포
    - 각 문서가 어떤 주제들로 이루어졌는지 확률 값으로 나타낸다.

In [9]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import LatentDirichletAllocation

In [10]:
count_vectorizer = CountVectorizer(max_df=0.1,              # 단어가 너무 자주(전체 문서의 10%) 등장하면 무시
                                   max_features=1000,       # 최대 피처 수
                                   min_df=2,                # 최소 문서 빈도(2 이상인 경우 포함)
                                   ngram_range=(1,2))       # 1-그램, 2-그램(연속된 두 단어 조합) 모두 사용

In [11]:
# 텍스트 데이터를 피처 벡터로 변환
# 문서-단어 행렬이 만들어짐.
feat_vect = count_vectorizer.fit_transform(token_list) # 각 문서가 어떤 단어를 얼마나 포함하는지 나타내는 벡터

In [12]:
print(feat_vect.shape)              # (문서수, 변환된 단어(피처) 수)
print(count_vectorizer.vocabulary_) # 피처 이름과 인덱스를 포함한 단어 출력

(96, 149)
{'하려면': np.int64(127), '뜨는데': np.int64(25), '않음': np.int64(64), '오늘 포인트': np.int64(77), '하려면 업데이트': np.int64(128), '수수료': np.int64(51), '매일': np.int64(28), '좋은데': np.int64(104), '업뎃': np.int64(73), '하래': np.int64(126), '했는데': np.int64(140), '이용': np.int64(81), '뜨고': np.int64(23), '같은데': np.int64(3), '언제': np.int64(68), '통장': np.int64(113), '잔액': np.int64(94), '재부팅': np.int64(98), '확인': np.int64(146), '하는데': np.int64(125), '많은': np.int64(26), '시간': np.int64(53), '확인 하는데': np.int64(147), '재미': np.int64(96), '하기': np.int64(122), '좋아요': np.int64(101), '사용 하기': np.int64(43), '실행': np.int64(54), '하면': np.int64(129), '광고': np.int64(8), '표시': np.int64(118), '눌러도': np.int64(17), '일주일': np.int64(84), '안되고': np.int64(57), '있는데': np.int64(86), '하고': np.int64(120), '있습니다': np.int64(87), '하고 있습니다': np.int64(121), '열려요': np.int64(75), '작동': np.int64(93), '무한': np.int64(30), '반복': np.int64(34), '열기': np.int64(74), '업데이트 무한': np.int64(69), '무한 반복': np.int64(31), '환급': np.int64(148), '안내': np.int64(56), '결제': np.int64(5), '요구': np.int64(79), '장난': np.int64(95), '이제': np.int64(82), '보기': np.int64(37), '사람': np.int64(41), '하는': np.int64(124), '입니다': np.int64(85), '알림': np.int64(66), '설정': np.int64(50), '해제': np.int64(139), '해도': np.int64(135), '클릭': np.int64(110), '안됨': np.int64(61), '클릭 하면': np.int64(111), '하면 업데이트': np.int64(130), '가요': np.int64(0), '이틀': np.int64(83), '플레이스토어': np.int64(119), '않네요': np.int64(63), '미션 오늘': np.int64(33), '포인트 미션': np.int64(117), '되는걸': np.int64(19), '들어가면': np.int64(21), '자꾸': np.int64(91), '해결': np.int64(133), '방법': np.int64(35), '업데이트 했는데': np.int64(72), '했는데 이번': np.int64(141), '자꾸 업데이트': np.int64(92), '해결 방법': np.int64(134), '사용 하는': np.int64(44), '은행': np.int64(80), '안되네요': np.int64(58), '했는데도': np.int64(143), '삭제': np.int64(45), '오늘 미션': np.int64(76), '안되네요 업데이트': np.int64(59), '했는데도 계속': np.int64(144), '계속 업데이트': np.int64(6), '증권': np.int64(108), '알람': np.int64(65), '않고': np.int64(62), '해도 안되네요': np.int64(136), '많음': np.int64(27), '계좌': np.int64(7), '금리': np.int64(14), '좋은': np.int64(102), '상품': np.int64(47), '주식': np.int64(107), '추가': np.int64(109), '부분': np.int64(39), '보는데': np.int64(38), '안되는': np.int64(60), '좋은 상품': np.int64(103), '화면': np.int64(145), '하네요': np.int64(123), '미션 업데이트': np.int64(32), '합니다': np.int64(132), '있어요': np.int64(89), '사용 있어요': np.int64(42), '그거': np.int64(13), '때문': np.int64(22), '어플': np.int64(67), '정작': np.int64(100), '구글': np.int64(10), '할수': np.int64(131), '무슨': np.int64(29), '구글플레이': np.int64(11), '버튼': np.int64(36), '주시': np.int64(105), '감사하겠습니다': np.int64(1), '구글플레이 토스': np.int64(12), '업데이트 버튼': np.int64(70), '주시 감사하겠습니다': np.int64(106), '해서': np.int64(137), '업데이트 해서': np.int64(71), '해서 했는데': np.int64(138), '같은': np.int64(2), '있지만': np.int64(90), '생각': np.int64(48), '광고 토스': np.int64(9), '서비스': np.int64(49), '오류': np.int64(78), '편리함': np.int64(115), '다시': np.int64(18), '삭제 다시': np.int64(46), '쉽게': np.int64(52), '뜨는': np.int64(24), '했는데 자꾸': np.int64(142), '누르면': np.int64(16), '됩니다': np.int64(20), '재미 있어요': np.int64(97), '금융': np.int64(15), '있어서': np.int64(88), '편리하고': np.int64(114), '편하게': np.int64(116), '거래': np.int64(4), '정보': np.int64(99), '불편해요': np.int64(40), '아예': np.int64(55), '토스 증권': np.int64(112)}

In [13]:
# 고유 단어 목록 출력
count_vectorizer.get_feature_names_out()

array(['가요', '감사하겠습니다', '같은', '같은데', '거래', '결제', '계속 업데이트', '계좌', '광고',
       '광고 토스', '구글', '구글플레이', '구글플레이 토스', '그거', '금리', '금융', '누르면', '눌러도',
       '다시', '되는걸', '됩니다', '들어가면', '때문', '뜨고', '뜨는', '뜨는데', '많은', '많음',
       '매일', '무슨', '무한', '무한 반복', '미션 업데이트', '미션 오늘', '반복', '방법', '버튼',
       '보기', '보는데', '부분', '불편해요', '사람', '사용 있어요', '사용 하기', '사용 하는', '삭제',
       '삭제 다시', '상품', '생각', '서비스', '설정', '수수료', '쉽게', '시간', '실행', '아예',
       '안내', '안되고', '안되네요', '안되네요 업데이트', '안되는', '안됨', '않고', '않네요', '않음',
       '알람', '알림', '어플', '언제', '업데이트 무한', '업데이트 버튼', '업데이트 해서',
       '업데이트 했는데', '업뎃', '열기', '열려요', '오늘 미션', '오늘 포인트', '오류', '요구', '은행',
       '이용', '이제', '이틀', '일주일', '입니다', '있는데', '있습니다', '있어서', '있어요', '있지만',
       '자꾸', '자꾸 업데이트', '작동', '잔액', '장난', '재미', '재미 있어요', '재부팅', '정보',
       '정작', '좋아요', '좋은', '좋은 상품', '좋은데', '주시', '주시 감사하겠습니다', '주식', '증권',
       '추가', '클릭', '클릭 하면', '토스 증권', '통장', '편리하고', '편리함', '편하게', '포인트 미션',
       '표시', '플레이스토어', '하고', '하고 있습니다', '하기', '하네요', '하는', '하는데', '하래',
       '하려면', '하려면 업데이트', '하면', '하면 업데이트', '할수', '합니다', '해결', '해결 방법',
       '해도', '해도 안되네요', '해서', '해서 했는데', '해제', '했는데', '했는데 이번', '했는데 자꾸',
       '했는데도', '했는데도 계속', '화면', '확인', '확인 하는데', '환급'], dtype=object)

In [14]:
# 모델 선언
# 토픽 수가 너무 적으면 서로 다른 이슈가 하나로 뭉칠 수 있음. 반대로 너무 많으면 비슷한 토픽이 여러 개로 쪼개져 해석이 어려워질 수 있음.
lda = LatentDirichletAllocation(n_components=5) # 추출할 토픽 5개

In [15]:
# 모델 학습
lda.fit(feat_vect)

LatentDirichletAllocation(n_components=5)

In [16]:
feature_names = count_vectorizer.get_feature_names_out()

for topic_index, topic in enumerate(lda.components_):
    print('Topic', topic_index + 1)
    topic_word_indexes = topic.argsort()[::-1]

    # 현재 토픽에서 가중치가 가장 높은 상위 10개 단어 인덱스만 선택
    top_index = topic_word_indexes[0:10]
    print(top_index)

    # 인덱스를 실제 단어로 변환
    feature_concat = [feature_names[i] for i in top_index]
    print(feature_concat)

Topic 1
[ 66   8 135 132 129  45  58   2  37  48]
['알림', '광고', '해도', '합니다', '하면', '삭제', '안되네요', '같은', '보기', '생각']
Topic 2
[140  87 101  73  72  51 102  57 137  32]
['했는데', '있습니다', '좋아요', '업뎃', '업데이트 했는데', '수수료', '좋은', '안되고', '해서', '미션 업데이트']
Topic 3
[ 30  89  31  34  95  79  96 148  51   6]
['무한', '있어요', '무한 반복', '반복', '장난', '요구', '재미', '환급', '수수료', '계속 업데이트']
Topic 4
[107  76 108 101  80 132  70  36 112 122]
['주식', '오늘 미션', '증권', '좋아요', '은행', '합니다', '업데이트 버튼', '버튼', '토스 증권', '하기']
Topic 5
[ 53 125  94 131 128  77  81 127 146 119]
['시간', '하는데', '잔액', '할수', '하려면 업데이트', '오늘 포인트', '이용', '하려면', '확인', '플레이스토어']

In [17]:
# LDA 모델에서 각 토픽을 대표하는 상위 단어를 출력하는 함수
def display_topic(model, feature_names, num_top_words):
    for topic_index, topic in enumerate(model.components_):
        print('Topic', topic_index + 1)
        topic_word_indexes = topic.argsort()[::-1]
        top_index = topic_word_indexes[0:num_top_words]
        print(top_index)
        feature_concat = [feature_names[i] for i in top_index]
        print(feature_concat)

In [18]:
# 학습된 LDA 모델에서 각 토픽별 상위 10개 단어를 출력
display_topic(lda, feature_names, 10)

Topic 1
[ 66   8 135 132 129  45  58   2  37  48]
['알림', '광고', '해도', '합니다', '하면', '삭제', '안되네요', '같은', '보기', '생각']
Topic 2
[140  87 101  73  72  51 102  57 137  32]
['했는데', '있습니다', '좋아요', '업뎃', '업데이트 했는데', '수수료', '좋은', '안되고', '해서', '미션 업데이트']
Topic 3
[ 30  89  31  34  95  79  96 148  51   6]
['무한', '있어요', '무한 반복', '반복', '장난', '요구', '재미', '환급', '수수료', '계속 업데이트']
Topic 4
[107  76 108 101  80 132  70  36 112 122]
['주식', '오늘 미션', '증권', '좋아요', '은행', '합니다', '업데이트 버튼', '버튼', '토스 증권', '하기']
Topic 5
[ 53 125  94 131 128  77  81 127 146 119]
['시간', '하는데', '잔액', '할수', '하려면 업데이트', '오늘 포인트', '이용', '하려면', '확인', '플레이스토어']

In [19]:
# LDA를 통해 각 문서(댓글)가 어떤 토픽에 속하는지 확인
# lda.transform(feat_vect) : 문서별 토픽 확률 분포 반환
topic_result = lda.transform(feat_vect)

sent_topic_list = []

# 각 문서에 대해 가장 높은 확률을 가진 토픽 번호와 그 확률을 추출.
for temp in range(len(topic_result)):
    topic = topic_result[temp].argmax()
    sent_topic_list.append([temp, topic, topic_result[temp].max()])


topic_df = pd.DataFrame(sent_topic_list, columns=['no', '토픽번호', '확률'])

topic_df['리뷰내용'] = df['리뷰내용']

topic_df

    no  토픽번호        확률                                        리뷰내용
0    0     4  0.865777  오늘의 포인트를 하려면 업데이트를.하라고 문구가 뜨는데 업데이트가 되지 않음
1    1     1  0.932754                                         좋아요
2    2     4  0.919731                                         편리함
3    3     2  0.599977                                       재미있어요
4    4     0  0.200000                                       잘모르겠음
..  ..   ...       ...                                         ...
91  91     1  0.838877                                         좋아요
92  92     0  0.838634                  좋아서요. 유익했고요. 앞으로 계속 애용할겁니다
93  93     3  0.797851       포인트도 많이 쌓이고 다양하게 사용할수 있어서 너무 편리하고 좋아요
94  94     4  0.799536                                          쪼아
95  95     0  0.897774      업데이트가 왜 안되는데? 사흘째 이러고 있으니 짜증이 나려고 하네요.

[96 rows x 4 columns]

In [20]:
# 토픽 단어만 보고 이름을 붙이는 것은 위험할 수 있음
topic0 = topic_df[topic_df['토픽번호']==0]
topic0.sort_values(by='확률', ascending=False).head(10)

    no  토픽번호        확률                                               리뷰내용
40  40     0  0.952666                                         계속 업데이트 요구
52  52     0  0.952489  일주일 미션에 참여하려면 앱 업데이트를 시켜야 한다고 해놓고 정작 구글 플레이스토어...
46  46     0  0.926992                         앱에 이거저거 계속 추가하더니 앱이 엄청무거워짐
25  25     0  0.919751                                              공유해요.
95  95     0  0.897774             업데이트가 왜 안되는데? 사흘째 이러고 있으니 짜증이 나려고 하네요.
15  15     0  0.885094                                                좋아요
47  47     0  0.865076                        이번주 미션 업데이트 언제 해줄건가요?? 늦어요.
49  49     0  0.839036                                       항상 잘사용하고 있어요
92  92     0  0.838634                         좋아서요. 유익했고요. 앞으로 계속 애용할겁니다
67  67     0  0.798193                                             좋아요~^^

In [ ]:
# %pip install pyLDAvis
# uv add pyLDAvis

In [21]:
# 시각화
import pyLDAvis.lda_model


# Jupyter Notebook 환경에서 시각화 활성화
pyLDAvis.enable_notebook()

vis = pyLDAvis.lda_model.prepare(
    lda,                            # 학습된 LDA 모델
    feat_vect,                      # CountVectorizer로 만든 문서-단어 행렬
    count_vectorizer                # 단어 사전 정보를 가진 vectorizer
)

pyLDAvis.display(vis)

In [ ]:
'''
왼쪽 : 토픽 간 거리 지도
- 원 하나가 하나의 토픽.
- 원의 크기 : 해당 토픽이 전체 문서에서 차지하는 비중
- 원끼리 가까우면 단어 분포가 비슷한 토픽
- 겹쳐 있으면 토픽이 명확히 분리되지 않았다는 뜻.

오른쪽 막대 그래프 : 선택된 토픽의 주요 단어
- 파란색 막대 : 전체 데이터에서 해당 단어가 등장한 빈도
- 빨간색 막대 : 선택된 토픽 안에서 해당 단어가 등장한 추정 빈도

오른쪽 위 λ 슬라이더
- λ = 1.0에 가까우면 해당 토픽 안에서 자주 등장하는 단어 중심으로 정렬
- λ = 0.0에 가까우면 전체 데이터에서는 덜 흔하지만 해당 토픽에서 특히 두드러지는 단어가 강조.
- 보통 0.5~0.6 전후로 조정하면서 보는 경우가 많음.
'''